//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommYouNity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public Community()
        {
            this.Members = new HashSet<Member>();
            this.SingleTasks = new HashSet<SingleTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string OfficerName { get; set; }
        public string ImgSrc { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<SingleTask> SingleTasks { get; set; }
    }
}
