//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommYouNity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Communities = new HashSet<Community>();
            this.SingleTasks = new HashSet<SingleTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Zip { get; set; }
        public string ImgSrc { get; set; }
        public string GoogleMap { get; set; }
    
        public virtual ICollection<Community> Communities { get; set; }
        public virtual ICollection<SingleTask> SingleTasks { get; set; }
    }
}
